
### str(tidy_d)
#### data.frame':	180 obs. of  68 variables:
 * Subject                                         : int  1 1 1 1 1 1 2 2 2 2 ...
 * Activity_id                                     : Factor w/ 6 levels "LAYING","SITTING",..: 1 2 3 4 5 6 1 2 3 4 ...
 * timeBodyAccelerator.mean...X                    : num  0.222 0.261 0.279 0.277 0.289 ...
 * timeBodyAccelerator.mean...Y                    : num  -0.04051 -0.00131 -0.01614 -0.01738 -0.00992 ...
 * timeBodyAccelerator.mean...Z                    : num  -0.113 -0.105 -0.111 -0.111 -0.108 ...
 * timeBodyAccelerator.std...X                     : num  -0.928 -0.977 -0.996 -0.284 0.03 ...
 * timeBodyAccelerator.std...Y                     : num  -0.8368 -0.9226 -0.9732 0.1145 -0.0319 ...
 * timeBodyAccelerator.std...Z                     : num  -0.826 -0.94 -0.98 -0.26 -0.23 ...
 * timeGravityAccelerator.mean...X                 : num  -0.249 0.832 0.943 0.935 0.932 ...
 * timeGravityAccelerator.mean...Y                 : num  0.706 0.204 -0.273 -0.282 -0.267 ...
 * timeGravityAccelerator.mean...Z                 : num  0.4458 0.332 0.0135 -0.0681 -0.0621 ...
 * timeGravityAccelerator.std...X                  : num  -0.897 -0.968 -0.994 -0.977 -0.951 ...
 * timeGravityAccelerator.std...Y                  : num  -0.908 -0.936 -0.981 -0.971 -0.937 ...
 * timeGravityAccelerator.std...Z                  : num  -0.852 -0.949 -0.976 -0.948 -0.896 ...
 * timeBodyAcceleratorJerk.mean...X                : num  0.0811 0.0775 0.0754 0.074 0.0542 ...
 * timeBodyAcceleratorJerk.mean...Y                : num  0.003838 -0.000619 0.007976 0.028272 0.02965 ...
 * timeBodyAcceleratorJerk.mean...Z                : num  0.01083 -0.00337 -0.00369 -0.00417 -0.01097 ...
 * timeBodyAcceleratorJerk.std...X                 : num  -0.9585 -0.9864 -0.9946 -0.1136 -0.0123 ...
  * timeBodyAcceleratorJerk.std...Y                 : num  -0.924 -0.981 -0.986 0.067 -0.102 ...
  * timeBodyAcceleratorJerk.std...Z                 : num  -0.955 -0.988 -0.992 -0.503 -0.346 ...
  * timeBodyGyro.mean...X                           : num  -0.0166 -0.0454 -0.024 -0.0418 -0.0351 ...
  * timeBodyGyro.mean...Y                           : num  -0.0645 -0.0919 -0.0594 -0.0695 -0.0909 ...
  * timeBodyGyro.mean...Z                           : num  0.1487 0.0629 0.0748 0.0849 0.0901 ...
  * timeBodyGyro.std...X                            : num  -0.874 -0.977 -0.987 -0.474 -0.458 ...
  * timeBodyGyro.std...Y                            : num  -0.9511 -0.9665 -0.9877 -0.0546 -0.1263 ...
  * timeBodyGyro.std...Z                            : num  -0.908 -0.941 -0.981 -0.344 -0.125 ...
  * timeBodyGyroJerk.mean...X                       : num  -0.1073 -0.0937 -0.0996 -0.09 -0.074 ...
  * timeBodyGyroJerk.mean...Y                       : num  -0.0415 -0.0402 -0.0441 -0.0398 -0.044 ...
  * timeBodyGyroJerk.mean...Z                       : num  -0.0741 -0.0467 -0.049 -0.0461 -0.027 ...
  * timeBodyGyroJerk.std...X                        : num  -0.919 -0.992 -0.993 -0.207 -0.487 ...
  * timeBodyGyroJerk.std...Y                        : num  -0.968 -0.99 -0.995 -0.304 -0.239 ...
  * timeBodyGyroJerk.std...Z                        : num  -0.958 -0.988 -0.992 -0.404 -0.269 ...
  * timeBodyAcceleratorMagnitude.mean..             : num  -0.8419 -0.9485 -0.9843 -0.137 0.0272 ...
  * timeBodyAcceleratorMagnitude.std..              : num  -0.7951 -0.9271 -0.9819 -0.2197 0.0199 ...
  * timeGravityAcceleratorMagnitude.mean..          : num  -0.8419 -0.9485 -0.9843 -0.137 0.0272 ...
  * timeGravityAcceleratorMagnitude.std..           : num  -0.7951 -0.9271 -0.9819 -0.2197 0.0199 ...
  * timeBodyAcceleratorJerkMagnitude.mean..         : num  -0.9544 -0.9874 -0.9924 -0.1414 -0.0894 ...
  * timeBodyAcceleratorJerkMagnitude.std..          : num  -0.9282 -0.9841 -0.9931 -0.0745 -0.0258 ...
  * timeBodyGyroMagnitude.mean..                    : num  -0.8748 -0.9309 -0.9765 -0.161 -0.0757 ...
  * timeBodyGyroMagnitude.std..                     : num  -0.819 -0.935 -0.979 -0.187 -0.226 ...
  * timeBodyGyroJerkMagnitude.mean..                : num  -0.963 -0.992 -0.995 -0.299 -0.295 ...
  * timeBodyGyroJerkMagnitude.std..                 : num  -0.936 -0.988 -0.995 -0.325 -0.307 ...
  * frequencyBodyAccelerator.mean...X               : num  -0.9391 -0.9796 -0.9952 -0.2028 0.0382 ...
  * frequencyBodyAccelerator.mean...Y               : num  -0.86707 -0.94408 -0.97707 0.08971 0.00155 ...
  * frequencyBodyAccelerator.mean...Z               : num  -0.883 -0.959 -0.985 -0.332 -0.226 ...
  * frequencyBodyAccelerator.std...X                : num  -0.9244 -0.9764 -0.996 -0.3191 0.0243 ...
  * frequencyBodyAccelerator.std...Y                : num  -0.834 -0.917 -0.972 0.056 -0.113 ...
  * frequencyBodyAccelerator.std...Z                : num  -0.813 -0.934 -0.978 -0.28 -0.298 ...
  * frequencyBodyAcceleratorJerk.mean...X           : num  -0.9571 -0.9866 -0.9946 -0.1705 -0.0277 ...
  * frequencyBodyAcceleratorJerk.mean...Y           : num  -0.9225 -0.9816 -0.9854 -0.0352 -0.1287 ...
  * frequencyBodyAcceleratorJerk.mean...Z           : num  -0.948 -0.986 -0.991 -0.469 -0.288 ...
  * frequencyBodyAcceleratorJerk.std...X            : num  -0.9642 -0.9875 -0.9951 -0.1336 -0.0863 ...
  * frequencyBodyAcceleratorJerk.std...Y            : num  -0.932 -0.983 -0.987 0.107 -0.135 ...
  * frequencyBodyAcceleratorJerk.std...Z            : num  -0.961 -0.988 -0.992 -0.535 -0.402 ...
  * frequencyBodyGyro.mean...X                      : num  -0.85 -0.976 -0.986 -0.339 -0.352 ...
  * frequencyBodyGyro.mean...Y                      : num  -0.9522 -0.9758 -0.989 -0.1031 -0.0557 ...
  * frequencyBodyGyro.mean...Z                      : num  -0.9093 -0.9513 -0.9808 -0.2559 -0.0319 ...
  * frequencyBodyGyro.std...X                       : num  -0.882 -0.978 -0.987 -0.517 -0.495 ...
  * frequencyBodyGyro.std...Y                       : num  -0.9512 -0.9623 -0.9871 -0.0335 -0.1814 ...
  * frequencyBodyGyro.std...Z                       : num  -0.917 -0.944 -0.982 -0.437 -0.238 ...
  * frequencyBodyAcceleratorMagnitude.mean..        : num  -0.8618 -0.9478 -0.9854 -0.1286 0.0966 ...
  * frequencyBodyAcceleratorMagnitude.std..         : num  -0.798 -0.928 -0.982 -0.398 -0.187 ...
  * frequencyBodyBodyAcceleratorJerkMagnitude.mean..: num  -0.9333 -0.9853 -0.9925 -0.0571 0.0262 ...
  * frequencyBodyBodyAcceleratorJerkMagnitude.std.. : num  -0.922 -0.982 -0.993 -0.103 -0.104 ...
  * frequencyBodyBodyGyroMagnitude.mean..           : num  -0.862 -0.958 -0.985 -0.199 -0.186 ...
  * frequencyBodyBodyGyroMagnitude.std..            : num  -0.824 -0.932 -0.978 -0.321 -0.398 ...
  * frequencyBodyBodyGyroJerkMagnitude.mean..       : num  -0.942 -0.99 -0.995 -0.319 -0.282 ...
  * frequencyBodyBodyGyroJerkMagnitude.std..        : num  -0.933 -0.987 -0.995 -0.382 -0.392 ...


#### 1. Merges the training and the test sets to create one data set.
created varibale for reading each file for test and train

`df_xtrain <- read.table('UCI HAR Dataset/train/X_train.txt', header = FALSE)`
`df_ytrain <- read.table('UCI HAR Dataset/train/y_train.txt', header = FALSE)`
`df_subtrain <- read.table('UCI HAR Dataset/train/subject_train.txt', header = FALSE)`

`df_xtest <- read.table('UCI HAR Dataset/test/X_test.txt', header = FALSE)`
`df_ytest <- read.table('UCI HAR Dataset/test/y_test.txt', header = FALSE)`
`df_subtest <- read.table('UCI HAR Dataset/test/subject_test.txt', header = FALSE)`

`train_all<-cbind(df_xtrain, df_ytrain,df_subtrain)`
`test_all<-cbind(df_xtest, df_ytest, df_subtest)`

#### 2.  combining test and train
`df_combined<-rbind(train_all, test_all)`

`features_read<-read.table("UCI HAR Dataset/features.txt")`
`y<-as.character(features_read *V2)`
`colnames(df_combined)[1:561]<-y`

`colnames(df_combined)[562]<-"Activity_id"`
`colnames(df_combined)[563]<-"Subject"`

#### 2. Extracts only the measurements on the mean and standard deviation for each measurement. 
`mean_sd<-df_combined[, grep("mean\\(\\)|std\\(\\)", colnames(df_combined))]`

#### 3. Uses descriptive activity names to name the activities in the data set
`act_label<-read.table("UCI HAR Dataset/activity_labels.txt")`

`df_combined *Activity_id[df_combined *Activity_id==1]<-"WALKING"`
`df_combined *Activity_id[df_combined *Activity_id==2]<-"WALKING_UPSTAIRS"`
`df_combined *Activity_id[df_combined *Activity_id==3]<-"WALKING_DOWNSTAIRS"`
`df_combined *Activity_id[df_combined *Activity_id==4]<-"SITTING"`
`df_combined *Activity_id[df_combined *Activity_id==5]<-"STANDING"`
`df_combined *Activity_id[df_combined *Activity_id==6]<-"LAYING"`

#### 4. Appropriately labels the data set with descriptive variable names. 

`names(df_combined) <- gsub("^t", "time", names(df_combined))`
`names(df_combined) <- gsub("^f", "frequency", names(df_combined))`
`names(df_combined) <- gsub("sma", "Signal magnitude area", names(df_combined))`
`names(df_combined) <- gsub("Acc", "Accelerator", names(df_combined))`
`names(df_combined) <- gsub("Mag", "Magnitude", names(df_combined))`


#### 5. From the data set in step 4, creates a second, 
####independent tidy data set with the average of each variable 
####for each activity and each subject.
####install.packages("reshape2")

`library(reshape2)`
`act_subj<-df_combined[, grep("Activity_id|Subject|mean\\(\\)|std\\(\\)", colnames(df_combined))]`
`new_df<-data.frame()`
`new_df<-melt(act_subj, id.vars = c("Activity_id", "Subject"))`


`subj_act_mean<-dcast(new_df, Subject + Activity_id ~variable, mean)`
`write.table(subj_act_mean, file = "tidydata.txt",row.name=FALSE)`
`tidy_d<-read.table("tidydata.txt", header = TRUE)`

